name: Daily Stock Predictions Email

on:
  schedule:
    # Run every weekday at 4:30 PM EST (after market close at 4 PM)
    # Cron format: minute hour day month day-of-week
    # 21:30 UTC = 4:30 PM EST (accounting for UTC-5)
    - cron: '30 21 * * 1-5'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  send-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy yfinance scikit-learn python-dotenv
    
    - name: Run email automation
      env:
        STREAMLIT_APP_URL: ${{ secrets.STREAMLIT_APP_URL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: |
        python email_automation.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: email-logs
        path: '*.log'
        retention-days: 7
